---
- name: Get the address of docker0
  shell: ip addr show docker0 | grep -Po 'inet \K[\d.]+'
  register: docker0_ip

- name: Remove the consul node
  docker:
    name: consul_node
    image: progrium/consul
    state: absent

- name: Start the consul bootstrap node
  when:
    - inventory_hostname in groups['consul_cluster']
    - inventory_hostname == consul_bootstrap_hostname
  docker:
    name: consul_node
    image: progrium/consul
    state: reloaded
    restart_policy: always
    net: host
    ports:
      - "{{ iputils_ip_internal }}:8300:8300"
      - "{{ iputils_ip_internal }}:8301:8301"
      - "{{ iputils_ip_internal }}:8301:8301/udp"
      - "{{ iputils_ip_internal }}:8302:8302"
      - "{{ iputils_ip_internal }}:8302:8302/udp"
      - "{{ iputils_ip_internal }}:8400:8400"
      - "{{ iputils_ip_internal }}:8500:8500"
      - "{{ iputils_ip_docker0 }}:53:53/udp"
    command: -server -advertise "{{ iputils_ip_external }}" -bootstrap-expect 3
    docker_api_version: 1.22

- name: Wait for the bootstrap node to be up
  shell: sleep 10
  when: inventory_hostname in groups['consul_cluster']

- name: Start the consul node
  when:
    - inventory_hostname in groups['consul_cluster']
    - inventory_hostname != consul_bootstrap_hostname
  docker:
    name: consul_node
    image: progrium/consul
    state: reloaded
    restart_policy: always
    net: host
    ports:
      - "{{ iputils_ip_internal }}:8300:8300"
      - "{{ iputils_ip_internal }}:8301:8301"
      - "{{ iputils_ip_internal }}:8301:8301/udp"
      - "{{ iputils_ip_internal }}:8302:8302"
      - "{{ iputils_ip_internal }}:8302:8302/udp"
      - "{{ iputils_ip_internal }}:8400:8400"
      - "{{ iputils_ip_internal }}:8500:8500"
      - "{{ iputils_ip_docker0 }}:53:53/udp"
    command: -server -advertise "{{ iputils_ip_external|mandatory }}" -join "{{ iputils_ip_consul_bootstrap|mandatory }}"
    docker_api_version: 1.22
