---
- name: Get the address of docker0
  shell: ip addr show docker0 | grep -Po 'inet \K[\d.]+'
  register: docker0_ip

- name: Start the consul bootstrap node
  when:
    - inventory_hostname in groups['consul_cluster']
    - inventory_hostname == consul_bootstrap_hostname
  docker:
    name: consul_node
    image: progrium/consul
    state: reloaded
    restart_policy: always
    ports:
      - "{{host_ip.stdout}}:8300:8300"
      - "{{host_ip.stdout}}:8301:8301"
      - "{{host_ip.stdout}}:8301:8301/udp"
      - "{{host_ip.stdout}}:8302:8302"
      - "{{host_ip.stdout}}:8302:8302/udp"
      - "{{host_ip.stdout}}:8400:8400"
      - "{{host_ip.stdout}}:8500:8500"
      - "{{docker0_ip.stdout}}:53:53/udp"
    command: -server -advertise "{{ host_ip.stdout }}" -bootstrap-expect 3
    docker_api_version: 1.22

- name: Start the consul node
  when:
    - inventory_hostname in groups['consul_cluster']
    - inventory_hostname != consul_bootstrap_hostname
  docker:
    name: consul_node
    image: progrium/consul
    state: reloaded
    restart_policy: always
    ports:
      - "{{host_ip.stdout}}:8300:8300"
      - "{{host_ip.stdout}}:8301:8301"
      - "{{host_ip.stdout}}:8301:8301/udp"
      - "{{host_ip.stdout}}:8302:8302"
      - "{{host_ip.stdout}}:8302:8302/udp"
      - "{{host_ip.stdout}}:8400:8400"
      - "{{host_ip.stdout}}:8500:8500"
      - "{{docker0_ip.stdout}}:53:53/udp"
    command: -server -advertise "{{ host_ip.stdout }}" -join "{{ bootstrap_ip.stdout }}"
    docker_api_version: 1.22
