---
- name: Check if the consul chain exists
  shell: iptables -t filter -L consul
  register: fw_consul
  ignore_errors: true

- name: Create the CONSUL chain
  shell: iptables -t filter -N consul && iptables -t filter -I INPUT 1 -j consul
  when: fw_consul.rc != 0

- name: Check if the docker_service is already opened
  shell: iptables -t filter -L consul | grep consul_service
  register: fw_consul_service
  ignore_errors: true

- name: Open port for docker communication on iptables
  iptables:
    table: filter
    chain: consul
    destination: "{{ host_ip.stdout }}/24"
    destination_port: 8500
    protocol: tcp
    state: present
    jump: ACCEPT
    comment: consul_service
  when: fw_consul_service.rc != 0
  # notify: reload iptables

- name: Iptables save
  shell: iptables-save > "{{ iptables_config }}"
