---
- name: Get the host ip internal
  shell: getent ahostsv4 $(hostname -f) | grep -v '127.0' | grep 'STREAM' | awk '{print $1}'
  register: host_ip_internal

- name: Get the host ip external (natted)
  shell: host $(hostname -f) | awk '{print $(NF)}'
  register: host_ip_external_natted
  when: host_natted

- name: Get the host ip external
  shell: getent ahostsv4  $(hostname -f) | grep -v '127.0' | grep 'STREAM' | awk '{print $1}'
  register: host_ip_external
  when: not host_natted

- name: Set the host ip
  shell: echo {{ host_ip_external_natted.stdout | default(host_ip_external.stdout) }}
  register: host_ip_external

- name: Get the consul bootstrap IP
  shell: getent ahostsv4 {{ consul_bootstrap_hostname }} | grep -v '127.0' | grep 'STREAM' | awk '{print $1}'
  register: bootstrap_ip
  when: not host_natted

- name: Get the consul bootstrap IP (natted)
  shell: host {{ consul_bootstrap_hostname }} | awk '{print $(NF)}'
  register: bootstrap_ip_natted
  when: host_natted

- name: Set the bootstrap ip
  shell: echo {{ bootstrap_ip_natted.stdout | default(bootstrap_ip.stdout) }}
  register: bootstrap_ip
  
